export const categories = [
  'eletricista',
  'encanador',
  'pedreiro',
  'pintor',
  'montador de móveis',
  'técnico em ar-condicionado',
  'diarista',
  'mototaxista',
  'motorista particular',
  'entregador',
  'freteiro',
  'guincheiro',
  'doceria',
  'marmitaria',
  'buffet',
  'confeitaria personalizada',
  'padaria artesanal',
  'cabeleireira',
  'manicure',
  'maquiadora',
  'designer de sobrancelhas',
  'esteticista',
  'professor particular',
  'professor de música',
  'professor de idiomas',
  'personal trainer',
  'técnico de informática',
  'técnico de celular',
  'instalador de câmeras',
  'pet shop',
  'chaveiro',
  'costureira',
  'babá',
  'cuidador de idosos',
  'lava a jato',
  'vidraceiro',
  'marceneiro',
  'fotógrafo',
  'film maker',
  'segurança',
  'garçom',
  'massoterapia',
  'psicólogo',
  'designer gráfico',
  'social media',
  'mecânico',
  'desenvolvedor de software',
  'analista de sistemas',
  'suporte técnico',
  'administrador de redes',
  'consultor de TI',
  'técnico em hardware',
  'web designer',
  'UX/UI designer',
  'especialista em segurança da informação',
  'programador mobile',
  'técnico em telecomunicações',
  'digital influencer',
  'redator freelancer',
  'assistente virtual',
  'montador e reparador de computadores',
  'técnico em manutenção de impressoras',
  'técnico em automação residencial',
  'técnico em manutenção de drones',
  'produtor de conteúdo digital',
  'instrutor de informática básica',
  'editor de vídeo',
  'animador digital',
  'tester de software',
  'gerente de projetos',
  'arquiteto de software',
  'administrador de banco de dados',
  ' técnico em redes de fibra óptica',
  'instalador de sistemas solares',
  'técnico em energias renováveis',
  'eletricista industrial',
  'técnico em manutenção industrial',
  'operador de máquinas',
  'ajudante geral',
  'soldador',
  'técnico em refrigeração',
  'consultor financeiro',
  'corretor de imóveis',
  'tradutor',
  'intérprete',
  'agente de viagens',
  'coach',
  'terapeuta ocupacional',
  'nutricionista',
  'auxiliar administrativo',
  'recepcionista',
  'assistente social',
]
