export const categories = [
  'eletricista',
  'encanador',
  'pedreiro',
  'pintor',
  'montador de móveis',
  'técnico em ar-condicionado',
  'diarista',
  'mototaxista',
  'motorista particular',
  'entregador',
  'freteiro',
  'guincheiro',
  'doceria',
  'marmitaria',
  'buffet',
  'confeitaria personalizada',
  'padaria artesanal',
  'cabeleireira',
  'manicure',
  'maquiadora',
  'designer de sobrancelhas',
  'esteticista',
  'professor particular',
  'professor de música',
  'professor de idiomas',
  'personal trainer',
  'técnico de informática',
  'técnico de celular',
  'instalador de câmeras',
  'pet shop',
  'chaveiro',
  'costureira',
  'babá',
  'cuidador de idosos',
  'lava a jato',
  'vidraceiro',
  'marceneiro',
  'fotógrafo',
  'film maker',
  'segurança',
  'garçom',
  'massoterapia',
  'psicólogo',
  'designer gráfico',
  'social media',
  'mecânico',
]
